(function(){!google.nocsixjs&&google.timers&&google.timers.load.t&&(google.timers.load.t.xjses=(new Date).getTime());})();
(function(){var e={},f=!1,g=function(b,c,a){try{var d=e[c[a][0]];if(d&&d[b])d[b](c[a][1])}catch(m){google.ml(m,!1,{cause:"m"+b,index:a,mid:c[a]&&c[a][0]})}};if(google.mc&&google.j)for(var h=0,i;i=google.mc[h++];)if(i[0]==29){google.j.cfg=i[1];break}var j=null,k,l;function n(){var b=j.value;l=b?eval("("+b+")"):{}}google.med=function(b){if(google.mc){for(var c=google.mc.concat(google.smc||[]),a=0,d=c.length;a<d;a++)g(b,c,b=="dispose"?d-a-1:a);if(b=="dispose")google.mc=null,google.smc=null;f=b!="dispose"}};
google.register=function(b,c){e[b]=c;if(google.smc&&f)for(var a=0,d=google.smc.length;a<d;a++)google.smc[a][0]==b&&g("init",google.smc,a)};google.save=function(b,c){if(j){var a;a:{if(google.mc){a=0;for(var d;d=google.mc[a++];)if(d[0]==b){a-=1;break a}}a=-1}if(a>=0)google.mc[a][1]=c,n(),l[k]=google.mc,j.value=google.stringify(l)}};google.initHistory=function(){k=google.kEI;if(j=document.getElementById("hcache"))if(n(),l[k])google.mc=l[k]};})();
(function(){var h=void 0,i=null;var k=function(a,b,c,d){a=a.split(".");c=c||window;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)if(!a.length&&b!==h){if(!c[e]||!d)c[e]=b}else c=c[e]?c[e]:c[e]={}};google.exportSymbol=function(a,b,c){k(a,b,c)};google.exportDefaultSymbol=function(a,b,c){k(a,b,c,!0)};google.exportProperty=function(a,b,c){a[b]=c};google.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c};var m={a:!1,h:!1,b:!1,opera:!1},n={a:!1,g:!1,m:!1,i:!1,j:!1,k:!1,e:!1,d:!1,c:!1,opera:!1};m.version="";n.version="";
var o=function(a){for(var b in m)m[b]=!1;for(var c in n)n[c]=!1;b=c=i;if(window.opera)m.opera=!0,n.opera=!0,c=b=/Opera\/(\S+)/;else if(a.indexOf("MSIE")>=0)m.a=!0,n.a=!0,c=b=/MSIE\s+([^\);]+)(\)|;)/;else if(a.indexOf("WebKit")>=0){m.b=!0;if(a.indexOf("Chrome")>=0)n.e=!0,b=/Chrome\/(\S+)/;else if(a.indexOf("Android")>=0&&a.indexOf("Mobile")<0)n.d=!0,b=/Version\/(\S+)/;else if(a.indexOf("Android")>=0&&a.indexOf("Mobile")>=0)n.c=!0,b=/Version\/(\S+)/;else if(a.indexOf("Safari")>=0)n.m=!0,b=/Version\/(\S+)/;
if(a.indexOf("iPad")>=0)n.i=!0;else if(a.indexOf("iPhone")>=0)n.j=!0;else if(a.indexOf("iPod")>=0)n.k=!0;c=/WebKit\/(\S+)/}else if(a.indexOf("Gecko")>=0){m.h=!0;if(a.indexOf("Firefox")>=0)n.g=!0,b=/Firefox\/(\S+)/;c=/rv\:([^\);]+)(\)|;)/}if(c)c=c.exec(a),m.version=c?c[1]:"";if(b)c=b.exec(a),n.version=c?c[1]:"";google.browser=google.browser||{};google.browser.engine={IE:m.a,GECKO:m.h,WEBKIT:m.b,OPERA:m.opera,version:m.version};google.browser.product={IE:n.a,FIREFOX:n.g,SAFARI:n.m,IPAD:n.i,IPHONE:n.j,
IPOD:n.k,CHROME:n.e,ANDROID_TABLET:n.d,ANDROID_MOBILE:n.c,OPERA:n.opera,version:n.version}};o(google.ua||window.navigator.userAgent);
var p=function(a,b){function c(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}for(var d=0,e=a.replace(/^\s+|\s+$/g,"").split("."),f=b.replace(/^\s+|\s+$/g,"").split("."),g=Math.max(e.length,f.length),j=0;d==0&&j<g;j++){var w=e[j]||"",l=f[j]||"",Q=RegExp("(\\d*)(\\D*)","g"),R=RegExp("(\\d*)(\\D*)","g");do{var q=Q.exec(w)||["","",""],r=R.exec(l)||["","",""];if(q[0].length==0&&r[0].length==0)break;d=c(q[1].length==0?0:parseInt(q[1],10),r[1].length==0?0:parseInt(r[1],10))||c(q[2].length==0,r[2].length==
0)||c(q[2],r[2])}while(d==0)}return d};google.browser=google.browser||{};google.browser.init=o;google.browser.compareVersions=p;google.browser.isEngineVersion=function(a){return p(m.version,a)>=0};google.browser.isProductVersion=function(a){return p(n.version,a)>=0};var s=/^(\w+)?(?:\.(.+))?$/,t=/^#([\w-]+)$/,u=function(a){return(document.getElementById("xjsc")||document.body).appendChild(a)},v=function(a,b){var c;if(c=a.match(t)){var d=document.getElementById(c[1]);return d?[d]:[]}c=a.match(s);d=c[2]&&RegExp("\\b"+c[2]+"\\b");c=(b||document).getElementsByTagName(c[1]||"*");for(var e=[],f=0,g;g=c[f++];)(!d||d.test(g.className))&&e.push(g);return e},x=function(a){return a.textContent||a.innerText||""};
google.dom={append:u,create:function(a,b){var c=a.match(s),d=document.createElement(c[1]);if(c[2])d.className=c[2];if(b)d.innerHTML=b;return d},get:function(a,b){return v(a,b)[0]||i},getAll:v,getText:x,insert:function(a,b,c){return b.parentNode.insertBefore(a,c?b.nextSibling:b)},remove:function(a){return a&&a.parentNode&&a.parentNode.removeChild(a)},set:function(a,b){for(var c=1;c<arguments.length;c+=2){var d=arguments[c],e=arguments[c+1],f=a.style;if(f&&d in f)f[d]=e;else if(d in a)a[d]=e;else if(m.a&&
f&&d=="opacity")a.zoom=1,d=(f.filter||"").replace(/alpha\([^)]*\)/,""),isNaN(parseFloat(e))||(d+="alpha(opacity="+e*100+")"),f.filter=d}return a}};google.listen=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)};google.unlisten=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c)};var y={},z=function(a,b){return a[1]-b[1]},A=function(a,b,c,d){var e=c===h?!0:c,f=c===!1,g=b&&b[0]===c;if(a in y){d===h&&(d=!1);var j;j=typeof d=="function"?d:function(a){return a===d};for(var w=0,l;l=y[a][w++];)if(l=l[0].apply(i,b||[]),f)e=e||l;else if(g&&(b[0]=l),e=l,j(e))return e}return typeof d=="function"?c:e};
google.msg={listen:function(a){var b=0,c=arguments,d=c.length;d%2==1&&(b=c[d-1]);for(var e=0;e<d-1;e+=2){var f=c[e];y[f]||(y[f]=[]);y[f].push([c[e+1],b]);y[f].sort(z)}},unlisten:function(a){for(var b=0;b<arguments.length-1;b+=2){var c=y[arguments[b]];if(c)for(var d=arguments[b+1],e=0;e<c.length;++e)if(c[e][0]==d){c.splice(e,1);break}}},send:A};var B,C=window.location.protocol+"//"+window.location.host,D=function(a,b,c){if(!A(32,[a,b,c],!1))try{if(RegExp("^("+C+")?/(url|aclk)\\?.*&rct=j(&|$)").test(a))if(b)google.r=1,b.location.replace(a);else{if(!B)B=document.createElement("iframe"),B.style.display="none",u(B);google.r=1;B.src=a}else window.location.href=a}catch(d){window.location.href=a}},E=function(){var a=window.location,b=a.hash?a.href.substr(a.href.indexOf("#")+1):"",c=b&&b.match(/(^|&)q=/),d=a.search?a.href.substr(a.href.indexOf("?")+
1).replace(/#.*/,""):"",b=(c?b:d).replace(/(^|&)(fp|tch)=[^&]*/g,"").replace(/^&/,"");return(c?"/search":a.pathname)+(b?"?"+b:"")},F=function(){var a=window.location;return a.hash?a.href.substr(a.href.indexOf("#")):""},G=function(a,b){var c,d=b?(c=b.indexOf("#"))>=0&&b.substr(c):F();return(c=d&&d.match("[#&]"+(b?"(q|fp)":"fp")+"=")?d.match("[#&]"+a+"=([^&]*)"):(b?b.match(/(\?|$)[^#]*/)[0]:window.location.search).match("[?&]"+a+"=([^&]*)"))?c[1]:i};
google.nav={go:D,search:function(a,b){var c=E().match(/[?&][\w\.\-~]+=([^&]*)/g),d={};if(c)for(var e=0,f;f=c[e++];){f=f.match(/([\w\.\-~]+?)=(.*)/);var g=f[2];d[f[1]]=g}for(f in a)a.hasOwnProperty(f)&&(g=a[f],g==i?delete d[f]:d[f]=g);c=["/search?"];e=!0;for(f in d)d.hasOwnProperty(f)&&(c.push((e?"":"&")+f+"="+d[f]),e=!1);D(c.join(""),h,b)},getLocation:E,getLocationHash:F,getParam:G,getQuery:function(){return G("q")}};var H=function(){return document.body.dir=="rtl"||document.dir=="rtl"},I=function(a,b,c){var d=c?"":0;if(m.a){if(d=b.replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()}),d=a.currentStyle&&a.currentStyle[d]||"",!c){if(!/^-?\d/.test(d))return 0;c=a.style.left;a.style.left=d;d=a.style.pixelLeft;a.style.left=c}}else{a=document.defaultView&&document.defaultView.getComputedStyle(a,"");if(m.b&&!a)return d;d=a.getPropertyValue(b);d=c?d:parseInt(d,10)}return d},J=function(a){var b;m.a?(b=a.style.pixelWidth||
0,b||(b=a.offsetWidth-I(a,"paddingLeft")-I(a,"paddingRight")-I(a,"borderLeft")-I(a,"borderRight"),b<0&&(b=0))):b=I(a,"width");return isNaN(b)?0:b},K=function(a){return a.offsetTop+(a.offsetParent?K(a.offsetParent):0)},L=function(a){return a.offsetLeft+(a.offsetParent?L(a.offsetParent):0)},M=function(a,b){return!a||!b?!1:RegExp("(^|\\s)"+b+"($|\\s)").test(a.className)};
google.style={getComputedStyle:I,getHeight:function(a){var b=I(a,"height");m.a&&!b&&(b=a.offsetHeight-I(a,"paddingTop")-I(a,"paddingBottom")-I(a,"borderTop")-I(a,"borderBottom"),b<0&&(b=0));return isNaN(b)?0:b},getWidth:J,getPageOffsetTop:K,getPageOffsetLeft:L,getPageOffsetStart:function(a){return L(a)+(H()?J(a):0)},getColor:function(a){return String(I(a,"color",!0))},hasClass:M,isRtl:H,addClass:function(a,b){if(a&&b&&!M(a,b)){var c=a.className==""?[]:a.className.split(/\s/);c.push(b);a.className=
c.join(" ")}},removeClass:function(a,b){if(M(a,b)){for(var c=a.className.split(/\s/),d=c.length-1;d>=0;d--)c[d]==b&&c.splice(d,1);a.className=c.join(" ")}}};var N={},O=["&","&amp;","<","&lt;",">","&gt;",'"',"&quot;","'","&#39;","{","&#123;"],P=function(a){return m.a?window.event.srcElement:a.target},S=function(a){!a||m.a?window.event.cancelBubble=!0:a.stopPropagation&&a.stopPropagation()},T=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}},U=function(a,b){S(b);var c=document.getElementById(a);if(c)c.style.display=="none"?(c.style.display=
"",N[a]=T(U,a),google.listen(document.body,"click",N[a])):(c.style.display="none",N[a]&&google.unlisten(document.body,"click",N[a]))};
google.util={escape:function(a){for(var b=0;b<O.length;b+=2)a=a.replace(RegExp(O[b],"g"),O[b+1]);return a},unescape:function(a){for(var b=0;b<O.length;b+=2)a=a.replace(RegExp(O[b+1],"g"),O[b]);return a},eventTarget:P,stopPropagation:S,getSelection:function(){return window.getSelection&&window.getSelection().toString()||document.selection&&document.selection.createRange&&document.selection.createRange().text},xjsol:function(a){if(google.sc&&(a=google.sc[a])){for(var b=0;b<a.cb.length;b++)a.cb[b]();
a.cb=[]}},xjsl:function(a,b){var c=google.sc[a];if(c)c.dl?b&&b():(b&&c.cb.push(b),google.dlj(c.u),c.dl=!0)},togglePopup:U,rateLimitFunction:function(a,b,c,d){var e=0,f=!1,g=i;return function(){var j=google.time();f?g=Array.prototype.slice.call(arguments,0):j-e>=c?(e=j,b.apply(a,arguments)):d&&(j=c-(j-e),f=!0,g=Array.prototype.slice.call(arguments,0),setTimeout(function(){f=!1;e=google.time();b.apply(a,g)},j))}}};var V=function(a,b,c){var d=RegExp("([?&])"+b+"=.*?(&|$)"),a=a.replace(/^([^#]*)(#|$)/,function(a,b){return b});return!a.match(d)&&c!=""?a+"&"+b+"="+c:a.replace(d,function(a,d,g){return c?d+b+"="+c+g:g?d:""})};
google.srp={isSerpLink:function(a){return/(search|images)/.test(a.href)},isSerpForm:function(a){return/\/search$/.test(a.action)},updateLinksWithParam:function(a,b,c,d){var e=document.getElementsByTagName("A");google.base_href=V(google.base_href,a,b);for(var f=0,g;g=e[f++];)if(c(g)){var j=m.a?g.innerHTML:h;g.href=V(g.href,a,b);if(j!=h)g.innerHTML=j}for(f=0;c=document.forms[f++];)if(d(c)){for(g=e=0;j=c.elements[g++];)if(j.name==a)e=1,b!=""?j.value=b:j.parentNode.removeChild(j);if(!e&&b!="")e=document.createElement("input"),
e.type="hidden",e.value=b,e.name=a,c.appendChild(e)}},qs:function(a){if(a=P(a)){for(;!M(a,"qs");)if(a=a.parentNode,!a||a==document.body)return;var b=document.getElementsByName("q"),c=b&&b[0],b=document.getElementById("tsf-oq");if(c&&b&&window.n&&(c=c.value,b=x(b),c&&c!=b))b=V(a.href,"q",encodeURIComponent(c)),a.href=V(b,"prmd","")}}};google.xhr=function(){var a=i;if(window.XMLHttpRequest)try{a=new XMLHttpRequest}catch(b){}if(!a)for(var c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0,e;e=c[d++];)try{a=new ActiveXObject(e);break}catch(f){}return a};})();
(function(){var e=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b};var f=function(){},j=function(a,b,c){switch(typeof b){case "string":i(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==null){c.push("null");break}if(e(b)=="array"){var h=b.length;c.push("[");for(var d="",g=0;g<h;g++)c.push(d),j(a,b[g],c),d=",";c.push("]");break}c.push("{");h="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(g=b[d],typeof g!="function"&&(c.push(h),i(d,c),c.push(":"),
j(a,g,c),h=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}},k={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},l=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g,i=function(a,b){b.push('"',a.replace(l,function(a){if(a in k)return k[a];var b=a.charCodeAt(0),d="\\u";b<16?d+="000":b<256?d+="00":b<4096&&(d+="0");return k[a]=d+b.toString(16)}),'"')};var m=[],n="/",o,p;function q(){var a=o.value;p=a?eval("("+a+")"):{}}var r=[];google.History={addPostInitCallback:function(a){r.push(a)},client:function(a){m.push(a);return m.length-1},initialize:function(a){n=a;p=null;if(o=document.getElementById("hcache")){q();for(a=0;a<m.length;++a)p&&p[n]&&p[n][a]&&m[a].call(null,p[n][a]);for(var a=0,b;b=r[a++];)b();r=[]}},save:function(a,b){if(o)q(),p[n]||(p[n]={}),p[n][a]=b,o.value=google.stringify(p)}};google.stringify=function(a){var b=[];j(new f,a,b);return b.join("")};})();
(function(){var f=0,h=0,i=[];function k(b){return b}
function l(){++h;for(var b=0,c;c=i[b++];){var g=google.time()-c.e;if(g>=c.c||c.a){for(var e=0,a=void 0;a=c.d[e++];)google.dom.set(a[0],a[1],a[6]?"rgb("+a[3].join(",")+")":a[3]+a[5]);c.a=!0;c.b&&c.b();c=0}else{for(e=0;a=c.d[e++];){var d=a[4](g/c.c);google.dom.set(a[0],a[1],(a[6]?"rgb("+[m(a[2][0],a[3][0],d,!0),m(a[2][1],a[3][1],d,!0),m(a[2][2],a[3][2],d,!0)].join(",")+")":m(a[2],a[3],d,a[5]=="px"))+a[5])}c=1}c||i.splice(--b,1)}i.length||(window.clearInterval(f),f=0)}
function m(b,c,g,e){b+=(c-b)*g;return e?Math.round(b):b}function n(b){for(var b=b.match(/#(..)(..)(..)/).slice(1),c=0;c<3;++c)b[c]=parseInt(b[c],16);return b}
google.fx={animate:function(b,c,g){for(var e=0,a;a=c[e++];){var d=typeof a[2]=="string";d?(a[2]=n(a[2]),a[3]=n(a[3]),a[5]=""):a[5]=a[5]==null?"px":a[5];a[4]=a[4]||k;a[6]=d;google.dom.set(a[0],a[1],d?"rgb("+a[2].join(",")+")":a[2]+a[5])}var j={c:b,b:g,e:google.time(),d:c};i.push(j);f=f||window.setInterval(l,15);return{finish:function(){if(!j.a)j.a=!0,l()}}},easeInAndOut:function(b){return(3-2*b)*b*b},easeOut:function(b){return 1-Math.pow(1-b,3)},getFrameCount:function(){return h},linear:k,unwrap:function(b){b.parentNode.parentNode.replaceChild(b,
b.parentNode)},wrap:function(b){var c=document.createElement("div");b.parentNode.replaceChild(c,b);c.appendChild(b);return c}};google.register(60,{dispose:function(){window.clearInterval(f);f=0;i=[]}});})();
(function(){google.event=google.event||{};google.event.back={};var d=[],f=[],g;function h(a,c){a&&(g[a]=c);google.save(81,g)}function j(){for(var a=[],c=0,b=d.length;c<b;c++){var e=d[c](g[f[c]]);e&&(a.length>0&&a.push(","),a.push(e))}google.a=1;a.push("&ei=",google.kEI);window.google.log("backbutton",a.join(""))}function k(a,c){return function(b){b=b||window.event;for(b=b.target||b.srcElement;b.parentNode&&b.tagName!="A";)b=b.parentNode;a(b,c?g[c]:null)}}var l=google.j&&google.j.en,m;
function n(a){(a.persisted||m)&&!l&&j();m=!0}google.event.back.register=function(a,c,b,e){e&&(g[e]={});for(var o=document.getElementsByTagName("a"),p=0,i;i=o[p++];)a(i)&&google.listen(i,"click",k(c,e));d.push(b);f.push(e)};google.event.back.saveHistory=h;
google.register(81,{init:function(){g={persisted:!1};google.a=0},history:function(a){a&&(g=a);if(g.persisted)j();else if(!g.persisted)g.persisted=!0,h(),window.addEventListener&&(window.addEventListener("pageshow",n,!1)